site_name: Typ
theme:
  name: cinder
  custom_dir: cinder-theme-ext
site_favicon: favicon.ico
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage:
    - Installation: usage/installation.md
    - Projects: usage/projects.md
    - Configuration: usage/configuration.md
    - Command Line: usage/command-line.md
    - Writing Markdown: usage/writing-markdown.md
  - Releases: releases.md
  - About: about.md
  - Contact: contact.md
site_dir: ../docs
extra:
  current_release_version: 0.0.5
  download_typ_latest_button_windows: <a href="https://link.www.typ-set.com/wD5Fm2"><button>Download Typ (Windows 64 bit)</button></a>
  download_typ_latest_button_linux: <a href="https://link.www.typ-set.com/ZMz1Wr"><button>Download Typ (Linux 64 bit)</button></a>
  
  r_0_0_5_windows: https://link.www.typ-set.com/wD5Fm2
  r_0_0_5_linux: https://link.www.typ-set.com/ZMz1Wr

  r_0_0_4: https://link.www.typ-set.com/S17sGH
  r_0_0_3: https://link.www.typ-set.com/BchghT
  r_0_0_2: https://link.www.typ-set.com/9uhL0q
  r_0_0_1: https://link.www.typ-set.com/fWknq4

google_analytics: ['UA-151371280-1', 'typ-set.com']
plugins:
  - search
  - markdownextradata: {}

copyright: © Mikiel Agutu 2019