site_name: Typ
theme:
  name: cinder
  custom_dir: cinder-theme-ext
site_favicon: favicon.ico
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage:
    - Installation: usage/installation.md
    - Projects: usage/projects.md
    - Configuration: usage/configuration.md
    - Command Line: usage/command-line.md
    - Writing Markdown: usage/writing-markdown.md
  - Releases: releases.md
  - About: about.md
  - Contact: contact.md
site_dir: ../docs
extra:
  current_release_version: 0.0.1
  download_typ_button: <a href="https://typ-releases.s3.eu-west-2.amazonaws.com/v0/typ.zip"><button>Download Typ</button></a>

plugins:
  - markdownextradata: {}

copyright: © Mikiel Agutu 2019