site_name: Typ
theme:
  name: cinder
  custom_dir: cinder-theme-ext
nav:
  - Home: index.md
  - About: about.md
  - Usage:
    - Installation: documentation/installation.md
    - Projects: documentation/projects.md
    - Command Line: documentation/command-line.md
site_dir: ../docs

copyright: © Mikiel Agutu 2019